language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - android-26

script:
   - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash) -t cf25376c-9432-4b0b-9989-5048288f8675
  